### ISSUE TITLE
vue-component crash when updating to Meteor 1.7

### ISSUE THREAD

**Issue by Armaldio** [meteor-vue/vue-meteor#326]
After the upgrade to Meteor 1.7, I'm unable to build or start Meteor while the package vue-component is there. 
I got infinite loading on the following line while starting: 

```
=> [HMR] Dev server listening on port 3003.
``` 
By enabling `--verbose`, I find that it's infinite working on `Processing files with akryum:vue-comp...`

If I try to build, I can see the real issue: 
`double free or corruption (out)`

**Comment by NGTmeaty** [comment]
Getting the same error. Wondering if anyone's got ideas for how to solve it!

**Comment by Billybobbonnet** [comment]
Similar error here. `meteor reset` or deleting meteor local folder didn't work.

**Comment by raphaelarias** [comment]
Same error @Akryum Would you be able to point us the right direction?

**Comment by iamstevendao** [comment]
@Akryum, will this error make it to be in your to-do list anytime soon?

**Comment by benjamn** [comment]
Until we figure this out, one possible workaround is to clone the `vue-component*` packages locally, so that they will be rebuilt using your current Meteor version:
```bash
cd path/to/your/app
mkdir -p packages
cd packages
git clone git@github.com:meteor-vue/vue-meteor.git
mv vue-meteor/packages/vue-component* .
rm -rf vue-meteor
cd ..
meteor run
```

**Comment by hluz** [comment]
@benjamn No luck for me... following your instructions while on 1.7.0.3 (on which I have no problem with `vue:component`), and this is what I get...

<details>
  <summary>errors:</summary><p>

```
 HLMacBP:app hluz$ meteor --settings /Users/hluz/Documents/Development/GreenS/meteor-vue/app-settings-.json
[[[[[ ~/Documents/Development/GreenS/meteor-vue/meteor-vue-app/app ]]]]]

=> Started proxy.
akryum:vue-component-dev-client: updating npm dependencies -- socket.io-client...
=> Meteor 1.7.0.4 is available. Update this project with 'meteor update'.
vue-component: updating npm dependencies -- postcss, postcss-load-config, postcss-selector-parser, postcss-modules, socket.io, async,
lodash, hash-sum, source-map, source-map-merger, generate-source-map, autoprefixer, vue-template-compiler, vue-template-es2015-compiler,
colors, app-module-path...
=> Started MongoDB.
=> [HMR] Dev server listening on port 3003.
Compiling /Users/hluz/Documents/Development/GreenS/meteor-vue/meteor-vue-app/app/imports/ui/components/App.vue with meteor-babel without a cache
[object Object]
    at Object.exports.compile (/Users/hluz/.meteor/packages/babel-compiler/.7.1.1.ig3ww6.p8h5k++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-babel/index.js:77:13)
    at Object.compile (packages/babel-compiler.js:44:29)
    at VueComponentTagHandler.getResults (packages/vue-component/plugin/tag-handler.js:128:30)
    at compileTags (packages/vue-component/plugin/vue-compiler.js:540:18)
    at compileOneFileWithContents (packages/vue-component/plugin/vue-compiler.js:549:12)
    at VueCompo.compileOneFile (packages/vue-component/plugin/vue-compiler.js:137:12)
    at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:54:34)
    at /Users/hluz/Documents/Development/GreenS/meteor-vue/meteor-vue-app/app/packages/vue-component/.npm/plugin/vue-component/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/hluz/Documents/Development/GreenS/meteor-vue/meteor-vue-app/app/packages/vue-component/.npm/plugin/vue-component/node_modules/async/dist/async.js:998:17)
    at /Users/hluz/Documents/Development/GreenS/meteor-vue/meteor-vue-app/app/packages/vue-component/.npm/plugin/vue-component/node_modules/async/dist/async.js:1002:9
    at Object.eachLimit$1 (/Users/hluz/Documents/Development/GreenS/meteor-vue/meteor-vue-app/app/packages/vue-component/.npm/plugin/vue-component/node_modules/async/dist/async.js:3182:24)
    at VueCompo.processFilesForTarget (packages/vue-component/plugin/vue-compiler.js:38:11)
    at __bottom_mark__ (/tools/utils/parse-stack.js:64:14)
    at /tools/isobuild/compiler-plugin.js:193:27
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at Profile.time (/tools/isobuild/compiler-plugin.js:181:22)
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/compiler-plugin.js:180:15
    at Function._.each._.forEach (/Users/hluz/.meteor/packages/meteor-tool/.1.7.0_3.g36hs8.89khd++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at CompilerPluginProcessor.runCompilerPlugins (/tools/isobuild/compiler-plugin.js:170:7)
    at ClientTarget._runCompilerPlugins (/tools/isobuild/bundler.js:1054:22)
    at buildmessage.enterJob (/tools/isobuild/bundler.js:834:34)
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:828:18)
    at /tools/isobuild/bundler.js:3019:14
    at /tools/isobuild/bundler.js:3108:20
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (/Users/hluz/.meteor/packages/meteor-tool/.1.7.0_3.g36hs8.89khd++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:3107:7
    at /tools/utils/buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:3000:31)
    at files.withCache (/tools/isobuild/bundler.js:2947:32)
    at Object.withCache (/tools/fs/files.js:1710:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2947:16)
    at Profile.run (/tools/runners/run-app.js:579:36)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:578:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:622:35)
    at AppRunner._fiber (/tools/runners/run-app.js:880:28)
    at /tools/runners/run-app.js:408:12
```
</p>
</details>

**Comment by vooteles** [comment]
Did some testing. My app, which includes vue-component, worked well on 1.7.0.3.

Then updated as follows:
```
meteor update --release 1.7.1-rc.2
meteor npm install --save @babel/runtime@latest

```

When I now run ```meteor``` in terminal (Ubuntu 16.04), the app starts fine and there's no errors in terminal, but when I go to http://localhost:3000 in the browser the page is loaded (i.e. the app's login screen is visible), but the page is stuck in an infinite reload loop.

**Comment by benjamn** [comment]
@vooteles If you run `meteor remove autoupdate hot-code-push`, does that help with the infinite reloading? There were some changes to the way the `autoupdate` package works in Meteor 1.7.1, so I'm wondering if that's the source of your issues.

**Comment by vooteles** [comment]
@benjamn , running ```meteor remove autoupdate hot-code-push``` in my app gave the following:

```
zx@desk:~/abc/asd$ meteor remove autoupdate hot-code-push
autoupdate is not a direct dependency in this project.
hot-code-push is not a direct dependency in this project.
```
And the reloading still happens in the browser.

Also, wanted to give my feedback on your previous temporary workaround proposal (cloning vue-component* packages locally) already earlier, but got bogged down yesterday. Ran the commands you mentioned and the workaround did not work for me either. Stumbles on the following in terminal:

<details><summary>errors:</summary>
```
zx@desk:~/abc/asd$ mkdir -p packages
zx@desk:~/abc/asd$ cd packages
zx@desk:~/abc/asd/packages$ git clone https://github.com/meteor-vue/vue-meteor.git
Cloning into 'vue-meteor'...
remote: Counting objects: 3672, done.
remote: Total 3672 (delta 0), reused 0 (delta 0), pack-reused 3672
Receiving objects: 100% (3672/3672), 1.60 MiB | 777.00 KiB/s, done.
Resolving deltas: 100% (2532/2532), done.
Checking connectivity... done.
zx@desk:~/abc/asd/packages$ mv vue-meteor/packages/vue-component* .
zx@desk:~/abc/asd/packages$ rm -rf vue-meteor
zx@desk:~/abc/asd/packages$ cd ..
zx@desk:~/abc/asd$ meteor run
[[[[[ ~/abc/asd ]]]]]                         

=> Started proxy.                             
akryum:vue-component-dev-client: updating npm dependencies -- socket.io-client...
vue-component: updating npm dependencies -- postcss, postcss-load-config, postcss-selector-parser, postcss-modules, socket.io, async,
lodash, hash-sum, source-map, source-map-merger, generate-source-map, autoprefixer, vue-template-compiler, vue-template-es2015-compiler,
colors, app-module-path...
=> Started MongoDB.                           
The handle(2) returned by watching /home/zx/abc/asd/packages/vue-component/.npm/plugin/vue-component/node_modules is the same with an already watched path(/home/zx/abc/asd/packages/vue-component/.npm/plugin/vue-component-new-gxafnu.xublo/node_modules)
=> [HMR] Dev server listening on port 3003.
=> Errors prevented startup:                  
   
   While processing files with akryum:vue-component (for target web.browser):
   /home/zx/abc/asd/packages/vue-component/.npm/plugin/vue-component/node_modules/vue-template-compiler/index.js:8:9: 
   
   Vue packages version mismatch:
   
   - vue@2.5.3
   - vue-template-compiler@2.5.13
   
   This may cause things to work incorrectly. Make sure to use the same version for both.
   If you are using vue-loader@>=10.0, simply update vue-template-compiler.
   If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
   
   at Object.<anonymous>
   (/home/zx/abc/asd/packages/vue-component/.npm/plugin/vue-component/node_modules/vue-template-compiler/index.js:8:9)
   at Module._compile (module.js:652:30)
   at Object.Module._extensions..js (module.js:663:10)
   at Module.load (module.js:565:32)
   at Module.Mp.load (/tools/tool-env/install-runtime.js:20:29)
   at tryModuleLoad (module.js:505:12)
   at Function.Module._load (module.js:497:3)
   at Module.require (module.js:596:17)
   at require (internal/module.js:11:18)
   at npmRequire (/tools/isobuild/bundler.js:2123:14)
   at Module.useNode (packages/modules-runtime.js:650:18)
   at index.js (<runJavaScript-23>:2224:8)
   at fileEvaluate (packages/modules-runtime.js:322:7)
   at Module.require (packages/modules-runtime.js:224:14)
   at require (packages/modules-runtime.js:244:21)
   at loadDefaultTemplateCompiler (packages/vue-component/plugin/vue-compiler.js:9:97)
   at loadPackage (packages/vue-component/plugin/vue-compiler.js:710:12)
   at compileOneFileWithContents (packages/vue-component/plugin/vue-compiler.js:546:22)
   at VueCompo.compileOneFile (packages/vue-component/plugin/vue-compiler.js:137:12)
   at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:54:34)
   at /home/zx/abc/asd/packages/vue-component/.npm/plugin/vue-component/node_modules/async/dist/async.js:3096:16
   at replenish (/home/zx/abc/asd/packages/vue-component/.npm/plugin/vue-component/node_modules/async/dist/async.js:998:17)
   at /home/zx/abc/asd/packages/vue-component/.npm/plugin/vue-component/node_modules/async/dist/async.js:1002:9
   at Object.eachLimit$1 (/home/zx/abc/asd/packages/vue-component/.npm/plugin/vue-component/node_modules/async/dist/async.js:3182:24)
   at VueCompo.processFilesForTarget (packages/vue-component/plugin/vue-compiler.js:38:11)
   
   
   While processing files with akryum:vue-component (for target web.browser.legacy):
   packages/vue-component/plugin/vue-compiler.js:547:36: compiler.parseComponent is not a function
   at compileOneFileWithContents (packages/vue-component/plugin/vue-compiler.js:547:36)
   at VueCompo.compileOneFile (packages/vue-component/plugin/vue-compiler.js:137:12)
   at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:54:34)
   at /home/zx/abc/asd/packages/vue-component/.npm/plugin/vue-component/node_modules/async/dist/async.js:3096:16
   at replenish (/home/zx/abc/asd/packages/vue-component/.npm/plugin/vue-component/node_modules/async/dist/async.js:998:17)
   at /home/zx/abc/asd/packages/vue-component/.npm/plugin/vue-component/node_modules/async/dist/async.js:1002:9
   at Object.eachLimit$1 (/home/zx/abc/asd/packages/vue-component/.npm/plugin/vue-component/node_modules/async/dist/async.js:3182:24)
   at VueCompo.processFilesForTarget (packages/vue-component/plugin/vue-compiler.js:38:11)
   
   
=> Your application has errors. Waiting for file change.
```
</details>

Not sure if there are some further steps I should take to fix this error, might be something obvious to more experienced developers. But hopefully this helps a bit.

**Comment by hluz** [comment]
Still looking for a solution to this issue...

**Comment by hluz** [comment]
@Akryum, @benjamn Further to the above, if you build and deploy works fine with 1.7.1x. The infinite loop is just when development mode. But of course renders the development with Vue components unworkable...

**Comment by Akryum** [comment]
Please update your packages and report back if it's not fixed.

**Comment by runarberg** [comment]
Still seeing constant refresh with:

* `akryum:vue-component` 0.14.1
* `akryum:vue-component-dev-client` 0.4.3
* `akryum:vue-component-dev-server`  0.1.2
* `vue-meteor-tracker` 2.0.0-beta.4
* meteor 1.8

**Comment by hluz** [comment]
> Still seeing constant refresh with:
> 
> akryum:vue-component 0.14.1
> akryum:vue-component-dev-client 0.4.3
> akryum:vue-component-dev-server 0.1.2
> vue-meteor-tracker 2.0.0-beta.4
> meteor 1.8

Same here...

**Comment by ch-lukas** [comment]
Me too

MacOS / Running Meteor in dev mode
akryum:vue-component 0.14.1
meteor 1.8

Checking out the stack it still seems to reference the underscore package .. thought that was history... just a through.

Compiling .../example/Accounts.vue with meteor-babel without a cache
[object Object]
    at Object.exports.compile (/.meteor/packages/akryum_vue-component/.0.14.1.ux8v8j.l8aes++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:77:13)
    at Object.compile (packages/babel-compiler.js:44:29)
    at VueComponentTagHandler.getResults (packages/vue-component/plugin/tag-handler.js:128:30)
    at compileTags (packages/vue-component/plugin/vue-compiler.js:540:18)
    at compileOneFileWithContents (packages/vue-component/plugin/vue-compiler.js:549:12)
    at VueCompo.compileOneFile (packages/vue-component/plugin/vue-compiler.js:137:12)
    at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:54:34)
    at /../.meteor/packages/akryum_vue-component/.0.14.1.ux8v8j.l8aes++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16
    at replenish (/../.meteor/packages/akryum_vue-component/.0.14.1.ux8v8j.l8aes++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:998:17)
    at /../.meteor/packages/akryum_vue-component/.0.14.1.ux8v8j.l8aes++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:1002:9
    at Object.eachLimit$1 (/../.meteor/packages/akryum_vue-component/.0.14.1.ux8v8j.l8aes++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3182:24)
    at VueCompo.processFilesForTarget (packages/vue-component/plugin/vue-compiler.js:38:11)
    at __bottom_mark__ (/tools/utils/parse-stack.js:69:14)
    at /tools/isobuild/compiler-plugin.js:198:27
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at Profile.time (/tools/isobuild/compiler-plugin.js:185:22)
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/compiler-plugin.js:184:15
    at Function._.each._.forEach (/../.meteor/packages/meteor-tool/.1.8.0.1qkev80.7154f++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at CompilerPluginProcessor.runCompilerPlugins (/tools/isobuild/compiler-plugin.js:174:7)
    at ClientTarget._runCompilerPlugins (/tools/isobuild/bundler.js:1102:22)
    at buildmessage.enterJob (/tools/isobuild/bundler.js:835:34)
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:829:18)
    at /tools/isobuild/bundler.js:3115:14
    at webArchs.forEach.arch (/tools/isobuild/bundler.js:3266:25)
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3220:14
    at /tools/utils/buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:3096:31)
    at files.withCache (/tools/isobuild/bundler.js:3041:32)
    at Object.withCache (/tools/fs/files.js:1712:12)
    at Object.bundle (/tools/isobuild/bundler.js:3041:16)
    at Profile.run (/tools/runners/run-app.js:569:24)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:568:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:610:35)
    at AppRunner._fiber (/tools/runners/run-a

**Comment by runarberg** [comment]
see also meteor/meteor#10257

**Comment by chris-visser** [comment]
I'm currently working around this by switching off HMR. This means that I'm leveraging Meteor's own system to do hot code pushing:

```
export NO_HMR=1
```

**Comment by devarthurribeiro** [comment]
+1

**Comment by nilsi** [comment]
Any news on this one? I'm clueless how to fix it but `export NO_HMR=1` at least help me to work temporarily

**Comment by vooteles** [comment]
+1. Cannot update to new Meteor version as long as this issue is unresolved.

**Comment by vadimmelnicuk** [comment]
Experiencing the same issue. Updated to Meteor 1.8.

**Comment by hluz** [comment]
> Please update your packages and report back if it's not fixed.

@Akryum, it is not fixed! ;-)

**Comment by bartmichu** [comment]
@Akryum definitely not fixed.

**Comment by nilsi** [comment]
Nice find @ch-lukas ! Is it possible to revert babel to the previous version to see if that fixes the problem or then Meteor will stop working?

**Comment by gustawdaniel** [comment]
@ch-lukas earlier I had problems with `npm update` command when `@babel/runtime` was updated up to `7.0.0-beta.55` so It was fixed at this version.

Meteor 1.8 ensured update of babel.

I confirmed that `export NO_HMR=1` works as workaround. 

Has this bug any influence on production code?

**Comment by ch-lukas** [comment]
@nilsi @gustawdaniel , regarding Babel. Ensure you have the latest version of the runtime `meteor npm install @babel/runtime@latest` instead of the beta 55 and also remove `meteor npm r --save-dev plugin-external-helpers` - also from your `.babelrc'. Then you shouldn't get any warnings from Meteor.

Regarding `export NO_HMR=1` as far as I can see in the src this command just skips the reload capabilities (which you need for dev) - hence totally production safe.

@Akryum, think I have found the error and fixed it with a pull request. The Meteor guys seem to have done a lot of work on the Babel side of things and one of the variables you were using to compare change versions has been removed - hence your code thought each change was new and required a new page reload - causing a loop.

**Comment by Billybobbonnet** [comment]
@ch-lukas @Akryum I just tested @ch-lukas PR locally and it is indeed fixing the issue.

Thank you 👍

**Comment by hluz** [comment]
@chris-visser, there is now an overlap in your PR (https://github.com/meteor-vue/vue-meteor/pull/335) and @ch-lukas PR (https://github.com/meteor-vue/vue-meteor/pull/338)...

**Comment by chris-visser** [comment]
I see... it might be better to merge this one. And only apply the HMR fix that stipped HMR from working if needed.
